security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
        App\Entity\User:
            algorithm: "auto"

    # password_hashers:
    #     App\Entity\User: 'auto'

    enable_authenticator_manager: true

    providers:
        users:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        login:
            pattern: ^/login
            stateless: true
            json_login:
                check_path: /login_check
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        dev:
            pattern: ^/_(profiler|wdt)
            security: false

        users:
            pattern: ^/users
            methods: [GET, PUT, PATCH, DELETE]
            stateless: true
            jwt: ~

        exchanges:
            pattern: ^/exchanges
            stateless: true
            lazy: true
            methods: [POST, GET, PUT, PATCH, DELETE]
            provider: users
            jwt: ~

        api:
            pattern: ^/api
            stateless: true
            provider: users
            jwt: ~

    access_control:
        - { path: ^/docs, roles: IS_AUTHENTICATED_ANONYMOUSLY } # Allows accessing the Swagger UI

        # Entity Users & Exchanges
        - {
              path: ^/users,
              roles: IS_AUTHENTICATED_FULLY,
              methods: [GET, PUT, PATCH, DELETE],
          }
        - { path: ^/exchanges,
            roles: [ROLE_USER, ROLE_ADMIN, IS_AUTHENTICATED_FULLY],
            methods: [POST, GET, PUT, PATCH, DELETE],
          }

        # Backend Admin
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: "^/admin/users", roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
